app:
  container_name: LocalEnvironment
  labels:
    - "pe-localenvironment-description=Local Environment for projects"
    - "pe-localenvironment-version=1"
  build: .
  ports:
    - "80:80"
  volumes:
    - /vagrant_data/public:/usr/local/apache2/htdocs/